# Default values for llamacpp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Namespace
namespace: llama

# Service configuration
service:
  name: llama-api
  type: LoadBalancer
  port: 8080
  targetPort: 8080

# Deployment configuration
deployment:
  name: llama-server
  replicas: 1
  image: llama-bonsai-pi:latest # built local image from fork https://github.com/PrismML-Eng/llama.cpp
  command: "/app/llama-server"
  modelFile: "/models/bonsai-8b.gguf"
  host: "0.0.0.0"
  port: 8080
  contextSize: 4096
  parallelSlots: 1
  # cacheTypeK: "q8_0"
  # cacheTypeV: "q8_0"
  # enableJinja: false
  # chatTemplate: "phi3"
  threads: 4
  resources:
    requests:
      memory: "3.5Gi"
      cpu: "1000m"
    limits:
      memory: "5Gi"
      cpu: "3800m"

# Volume configuration
volume:
  name: model-storage
  hostPath: "/home/iniweb/llm-models"
  type: Directory