# Default values for llamacpp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Namespace
namespace: llama

# Service configuration
service:
  name: llama-api
  type: LoadBalancer
  port: 8080
  targetPort: 8080

# Deployment configuration
deployment:
  name: llama-server
  replicas: 1
  image: ghcr.io/ggml-org/llama.cpp:server
  imagePullPolicy: Always
  command: "/app/llama-server"
  alias: "unsloth/gemma-4-26B-A4B-it-qat-GGUF"
  modelFile: "/models/gemma-4-E4B-it-qat-UD-Q4_K_XL.gguf"
  mmprojFile: "/models/mmproj-BF16.gguf"
  host: "0.0.0.0"
  port: 8080
  contextSize: 4096
  parallelSlots: 1
  temp: 1.0
  topP: 0.95
  topK: 64
  chatTemplateKwargs: '{"enable_thinking":true}'
  # cacheTypeK: "q8_0"
  # cacheTypeV: "q8_0"
  # enableJinja: false
  # chatTemplate: "phi3"
  threads: 4
  resources:
    requests:
      memory: "3.5Gi"
      cpu: "1000m"
    limits:
      memory: "5Gi"
      cpu: "3800m"

# Volume configuration
volume:
  name: model-storage
  hostPath: "/home/iniweb/llm-models"
  type: Directory